### ISSUE TITLE
More updates and check renv leftovers

### ISSUE THREAD

**Issue by grantmcdermott** [hollina/ehec-intro-to-r#3]
Hey @hollina I just pushed a couple more updates to the intro notebook. Could you please knit for the Stata stuff.

Two other things before you do:

1. I saw some leftover (or recently added?) renv scaffolding,which I deleted. If you pull my changes, it should get rid of that for you too. But, just to be sure, I recommend running `renv::deactivate()` after you pull.
2. I see the knitted document is producing some warnings that I don't get on my side. Particularly, with the adjusted SE example using modelsummary. I suspect this could be related to the renv issue above, but I've just gone ahead and turned warnings off globally. It may be worth updating your packages (or just sandwich, lmtest, and modelsummary) if you are using older versions.

**Comment by hollina** [comment]
Recompiled and pushed

1. weird. I ran `renv::deactivate()`, but it's not clear to me if it did anything. It had me commit a number of libraries.
2. modelsummary et al seem to be up to date. 

No more warnings in code, but you did turn them off.  Hopefully the deactivate did something on the backend.

**Comment by grantmcdermott** [comment]
Hmmm, I still see it there and the modelsummary output doesn't look quite right (e.g. the modelplot SEs are all the same).

Tell you what: I might just update the whole renv scaffolding so that it reflects my library versions and makes things easy for everyone to install. We're a bit betwixt and between now. I'll let you know as soon as I'm done.

**Comment by hollina** [comment]
I see now. This had to be suppressed because the warnings were off. 

<img width="893" alt="Screen Shot 2021-07-14 at 8 30 03 PM" src="https://user-images.githubusercontent.com/8823995/125709585-9a933675-9df7-4f95-9f19-f51e7ed509e2.png">

**Comment by grantmcdermott** [comment]
Closing after our Zoom chat earlier. Might be worth deleting the cache and knitting one last time to fix the modelplot, but up to you ;-)

**Comment by hollina** [comment]
Thanks again for helping fix those issues. I knit once more just to be sure. :)
